// priority: 1

const wetFoods = [
  "aquaculture:turtle_soup",
  "farmersdelight:chicken_soup",
  "farmersdelight:noodle_soup",
  "farmersdelight:pumpkin_soup",
  "farmersdelight:vegetable_soup",
  "fruitsdelight:bayberry_soup",
  "minecraft:beetroot_soup",
  "farmersdelight:apple_cider",
  "farmersdelight:baked_cod_stew",
  "farmersdelight:beef_stew",
  "farmersdelight:fish_stew",
  "fruitsdelight:fig_chicken_stew",
  "fruitsdelight:mangosteen_tea",
  "minecraft:mushroom_stew",
  "minecraft:rabbit_stew",
  "minecraft:suspicious_stew",
  "farmersdelight:bone_broth",
  "fruitsdelight:mango_milkshake",
  "fruitsdelight:kiwi_juice",
  "fruitsdelight:lemon_juice",
  "fruitsdelight:orange_juice",
  "fruitsdelight:pear_juice",
  "farmersdelight:melon_popsicle",
  "fruitsdelight:kiwi_popsicle",
  "fruitsdelight:hawberry_tea",
  "fruitsdelight:lychee_cherry_tea",
  "fruitsdelight:mango_tea",
  "fruitsdelight:peach_tea",
  "fruitsdelight:hamimelon_juice",
  "minecraft:melon_slice"
]