StartupEvents.registry('item', event => {
	event.create('kubejs:cert_cook_diamond')
	event.create('kubejs:cert_fish_diamond')
  event.create('kubejs:cert_ani_diamond')
	event.create('kubejs:cert_flora_diamond')
	event.create('kubejs:cert_mining_diamond')
	// event.create('kubejs:cert_decocom_diamond').displayName('Common Deco Collection Certificate')
	// event.create('kubejs:cert_decorare_diamond').displayName('Rare Deco Collection Certificate')
	// event.create('kubejs:cert_hat_diamond').displayName('Hat Collection Certificate')
	// event.create('kubejs:cert_clothes_diamond').displayName('Clothing Collection Certificate')
})