ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'aquaculture:atlantic_cod', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:pink_salmon', 
      'aquaculture:rainbow_trout', 
      'aquaculture:bayad', 
      'aquaculture:gar', 
      'aquaculture:muskellunge', 
      'aquaculture:tambaqui', 
      'aquaculture:red_grouper'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for5Tickets')
    ])
  event.add(
    [
      'aquaculture:blackfish', 
      'aquaculture:minnow'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for3Tickets')
    ])
  event.add(
    [
      'aquaculture:atlantic_herring', 
      'aquaculture:synodontis', 
      'aquaculture:bluegill', 
      'aquaculture:perch', 
      'aquaculture:piranha', 
      'minecraft:tropical_fish', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for2Tickets')
    ])
  event.add(
    [
      'aquaculture:pollock', 
      'aquaculture:boulti', 
      'aquaculture:smallmouth_bass', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:jellyfish', 
      'aquaculture:leech'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for4Tickets')
    ])
  event.add(
    [
      'aquaculture:capitaine', 
      'aquaculture:arapaima', 
      'aquaculture:arrau_turtle', 
      'aquaculture:box_turtle', 
      'aquaculture:starshell_turtle'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for6Tickets')
    ])
  event.add(
    [
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma', 
      'minecraft:cod', 
      'minecraft:salmon'
    ],
    [
      Text.translate('fishCraftingTableSell.youCanSell2OfTheseFishes'), 
      Text.translate('fishCraftingTableSell.for1Tickets')
    ])

})