global.menus = [
  'kubejs:small_menu',
  'kubejs:medium_menu',
  'kubejs:large_menu',
]

global.menuInfo = {
  'kubejs:small_menu': {
    numDishes: 4,
    numTickets: 6,
    desc: 'npcFoodPurchase.smallOrder',
    size: 'npcFoodPurchase.small'
  },
  'kubejs:medium_menu': {
    numDishes: 8,
    numTickets: 16,
    desc: 'npcFoodPurchase.mediumOrder',
    size: 'npcFoodPurchase.medium'
  },
  'kubejs:large_menu': {
    numDishes: 16,
    numTickets: 64,
    desc: 'npcFoodPurchase.largeOrder',
    size: 'npcFoodPurchase.large'
  },
}

global.customerFoods = [
  'farmersdelight:apple_pie',
  'farmersdelight:sweet_berry_cheesecake',
  'farmersdelight:chocolate_pie',
  'farmersdelight:sweet_berry_cookie',
  'farmersdelight:honey_cookie',
  'farmersdelight:melon_popsicle',
  'farmersdelight:glow_berry_custard',
  'farmersdelight:fruit_salad',
  'farmersdelight:mixed_salad',
  'farmersdelight:nether_salad',
  'farmersdelight:barbecue_stick',
  'farmersdelight:egg_sandwich',
  'farmersdelight:chicken_sandwich',
  'farmersdelight:hamburger',
  'farmersdelight:bacon_sandwich',
  'farmersdelight:mutton_wrap',
  'farmersdelight:dumplings',
  'farmersdelight:stuffed_potato',
  'farmersdelight:cabbage_rolls',
  'farmersdelight:bone_broth',
  'farmersdelight:beef_stew',
  'farmersdelight:chicken_soup',
  'farmersdelight:vegetable_soup',
  'farmersdelight:fish_stew',
  'farmersdelight:fried_rice',
  'farmersdelight:pumpkin_soup',
  'farmersdelight:baked_cod_stew',
  'farmersdelight:noodle_soup',
  'farmersdelight:bacon_and_eggs',
  'farmersdelight:pasta_with_meatballs',
  'farmersdelight:pasta_with_mutton_chop',
  'farmersdelight:mushroom_rice',
  'farmersdelight:roasted_mutton_chops',
  'farmersdelight:vegetable_noodles',
  'farmersdelight:steak_and_potatoes',
  'farmersdelight:ratatouille',
  'farmersdelight:squid_ink_pasta',
  'farmersdelight:grilled_salmon',
  'farmersdelight:roast_chicken_block',
  'farmersdelight:stuffed_pumpkin_block',
  'farmersdelight:honey_glazed_ham_block',
  'farmersdelight:shepherds_pie_block',
  'farmersdelight:rice_roll_medley_block',
  'refurbished_furniture:cheese_toastie',
  'refurbished_furniture:sweet_berry_jam_toast',
  'refurbished_furniture:glow_berry_jam_toast',
  'refurbished_furniture:cooked_vegetable_pizza',
  'refurbished_furniture:cooked_meatlovers_pizza',
  'refurbished_furniture:cheese_toastie',
  'refurbished_furniture:sweet_berry_jam_toast',
  'refurbished_furniture:glow_berry_jam_toast',
  'refurbished_furniture:cooked_vegetable_pizza',
  'refurbished_furniture:cooked_meatlovers_pizza',
  "dumplings_delight:pork_cabbage_boiled_dumpling",
  "dumplings_delight:pork_kelp_boiled_dumpling",
  "dumplings_delight:pork_potato_boiled_dumpling",
  "dumplings_delight:pork_fennel_boiled_dumpling",
  "dumplings_delight:cod_boiled_dumpling",
  "dumplings_delight:salmon_boiled_dumpling",
  "dumplings_delight:calamari_boiled_dumpling",
  "dumplings_delight:pufferfish_boiled_dumpling",
  "dumplings_delight:tomato_egg_boiled_dumpling",
  "dumplings_delight:eggplant_egg_boiled_dumpling",
  "dumplings_delight:mushroom_boiled_dumpling",
  "dumplings_delight:fungus_boiled_dumpling",
  "dumplings_delight:garlic_chive_egg_boiled_dumpling",
  "dumplings_delight:dandelion_leaf_boiled_dumpling",
  "dumplings_delight:dumpling_medley",
  "dumplings_delight:beef_tomato_boiled_dumpling",
  "dumplings_delight:mutton_boiled_dumpling",
  "dumplings_delight:chicken_mushroom_boiled_dumpling",
  "dumplings_delight:rabbit_meat_boiled_dumpling",
  "dumplings_delight:pork_carrot_wonton",
  "dumplings_delight:pork_mushroom_wonton",
  "dumplings_delight:pork_cabbage_wonton",
  "fruitsdelight:apple_jello",
  "fruitsdelight:blueberry_jello",
  "fruitsdelight:glowberry_jello",
  "fruitsdelight:hamimelon_jello",
  "fruitsdelight:melon_jello",
  "fruitsdelight:hawberry_jello",
  "fruitsdelight:lychee_jello",
  "fruitsdelight:mango_jello",
  "fruitsdelight:orange_jello",
  "fruitsdelight:peach_jello",
  "fruitsdelight:pear_jello",
  "fruitsdelight:persimmon_jello",
  "fruitsdelight:pineapple_jello",
  "fruitsdelight:lemon_jello",
  "fruitsdelight:cranberry_jello",
  "fruitsdelight:mangosteen_jello",
  "fruitsdelight:sweetberry_jello",
  "fruitsdelight:chorus_jello",
  "fruitsdelight:bayberry_jello",
  "fruitsdelight:kiwi_jello",
  "fruitsdelight:fig_jello",
  "fruitsdelight:durian_jello",
  "fruitsdelight:hamimelon_juice",
  "fruitsdelight:hawberry_tea",
  "fruitsdelight:orange_juice",
  "fruitsdelight:lemon_juice",
  "fruitsdelight:pear_juice",
  "fruitsdelight:mango_tea",
  "fruitsdelight:peach_tea",
  "fruitsdelight:lychee_cherry_tea",
  "fruitsdelight:mangosteen_tea",
  "fruitsdelight:bayberry_soup",
  "fruitsdelight:kiwi_juice",
  "fruitsdelight:bellini_cocktail",
  "fruitsdelight:blueberry_custard",
  "fruitsdelight:hamimelon_shaved_ice",
  "fruitsdelight:blueberry_muffin",
  "fruitsdelight:cranberry_muffin",
  "fruitsdelight:lemon_tart",
  "fruitsdelight:fig_tart",
  "fruitsdelight:persimmon_cookie",
  "fruitsdelight:lemon_cookie",
  "fruitsdelight:cranberry_cookie",
  "fruitsdelight:bayberry_cookie",
  "fruitsdelight:fig_pudding",
  "fruitsdelight:hamimelon_popsicle",
  "fruitsdelight:kiwi_popsicle",
  "fruitsdelight:hawberry_roll",
  "fruitsdelight:hawberry_stick",
  "fruitsdelight:mango_milkshake",
  "fruitsdelight:mango_salad",
  "fruitsdelight:pineapple_fried_rice"
]